config/routes.rb
Rails.application.routes.draw do
  resources :pixels
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "users/registrations"}
  get 'pagamento/index'
  #match '*path' => redirect('/'), via: :get
  match ':not_found' => redirect('/'), via: :get

  #resources :seguros
  resources :orcamentos
  #get 'orcamentos/new'

	scope "orcamentos/:_id" do
	resources :steps
	end

  #resources :steps
  root 'orcamentos#new'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pixel.rb
class Pixel
  include Mongoid::Document
  field :text, type: String
end

app/controllers/pixels_controller.rb
class PixelsController < ApplicationController
  before_action :set_pixel, only: [:show, :edit, :update, :destroy]

  # GET /pixels
  # GET /pixels.json
  def index
    @pixels = Pixel.all
  end

  # GET /pixels/1
  # GET /pixels/1.json
  def show
  end

  # GET /pixels/new
  def new
    @pixel = Pixel.new
  end

  # GET /pixels/1/edit
  def edit
  end

  # POST /pixels
  # POST /pixels.json
  def create
    @pixel = Pixel.new(pixel_params)

    respond_to do |format|
      if @pixel.save
        format.html { redirect_to @pixel, notice: 'Pixel was successfully created.' }
        format.json { render :show, status: :created, location: @pixel }
      else
        format.html { render :new }
        format.json { render json: @pixel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pixels/1
  # PATCH/PUT /pixels/1.json
  def update
    respond_to do |format|
      if @pixel.update(pixel_params)
        format.html { redirect_to @pixel, notice: 'Pixel was successfully updated.' }
        format.json { render :show, status: :ok, location: @pixel }
      else
        format.html { render :edit }
        format.json { render json: @pixel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pixels/1
  # DELETE /pixels/1.json
  def destroy
    @pixel.destroy
    respond_to do |format|
      format.html { redirect_to pixels_url, notice: 'Pixel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pixel
      @pixel = Pixel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pixel_params
      params.require(:pixel).permit(:text)
    end
end

app/helpers/pixels_helper.rb
module PixelsHelper
end

app/views/pixels/_form.html.erb
<%= form_for(pixel) do |f| %>
  <% if pixel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pixel.errors.count, "error") %> prohibited this pixel from being saved:</h2>

      <ul>
      <% pixel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pixels/_index.html.erb
    <% Pixel.all.each do |pixel| %>
      <%=raw pixel.text.html_safe %>
    <% end %>

app/views/pixels/edit.html.erb
<h1>Editing Pixel</h1>

<%= render 'form', pixel: @pixel %>

<%= link_to 'Show', @pixel %> |
<%= link_to 'Back', pixels_path %>

app/views/pixels/new.html.erb
<h1>New Pixel</h1>

<%= render 'form', pixel: @pixel %>

<%= link_to 'Back', pixels_path %>

app/views/pixels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @pixel.text %>
</p>

<%= link_to 'Edit', edit_pixel_path(@pixel) %> |
<%= link_to 'Back', pixels_path %>