config/routes.rb
Rails.application.routes.draw do
  resources :pixels
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "users/registrations"}
  get 'pagamento/index'
  #match '*path' => redirect('/'), via: :get
  match ':not_found' => redirect('/'), via: :get

  #resources :seguros
  resources :orcamentos
  #get 'orcamentos/new'

	scope "orcamentos/:_id" do
	resources :steps
	end

  #resources :steps
  root 'orcamentos#new'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/orcamento.rb
class Orcamento

  include Mongoid::Document
  field :current_step, type: String
  field :cli_name, type: String
  field :cli_email, type: String
  field :cli_tel, type: String
  field :cli_cpf, type: String
  field :cli_pais, type: String
  field :cli_sexo, type: String
  field :cli_cep, type: String
  field :cli_end, type: String
  field :cli_end_number, type: Integer
  field :cli_end_compl, type: String
  field :cli_end_cidade, type: String
  field :cli_end_bairro, type: String
  field :vei_tipo, type: String
  field :vei_nacionalidade, type: String
  field :vei_marca, type: String
  field :vei_veiculo, type: String
  field :vei_modelo_ano, type: String
  field :vei_preco, type: Float
  field :vei_tipo_uso, type: String
  field :vei_placa, type: String
  field :seguro_plan, type: String
  field :seguro_preco_default, type:Float
  field :seguro_preco_silver, type:Float
  field :seguro_preco_pro, type:Float
  field :data_pgto, type: String
  field :seguro_preco_final, type:Float
  field :seg_car_reboque_300, type:Boolean
  field :seg_car_reboque_500, type:Boolean
  field :seg_car_terceiros_50k, type:Boolean
  field :seg_car_vidros, type:Boolean
  field :seg_car_reserva_7d, type:Boolean
  field :seg_car_reserva14, type:Boolean
  field :seg_moto_reboque_300, type:Boolean
  field :seg_moto_reboque_500, type:Boolean
  field :seg_cam_reboque_300, type:Boolean
  field :seg_cam_terceiros_50k, type:Boolean
  field :seg_cam_terceiros_100k, type:Boolean
  field :seg_cam_terceiros_200k, type:Boolean
  field :seg_cam_vidros, type:Boolean
  field :seg_car_imp_reboque_300, type:Boolean
  field :seg_car_imp_reboque_500, type:Boolean
  field :seg_car_imp_terceiros_50k, type:Boolean
  field :seg_car_imp_vidros, type:Boolean
  field :seg_car_imp_reserva_7d, type:Boolean
  field :seg_car_imp_reserva14, type:Boolean


  
  after_update :set_seg_preco,  :check_idade_carro 
  #validates_presence_of :vei_tipo, if: :select_veicle_type?



  def check_idade_carro
  end

  def set_seg_preco
    if(self.current_step == 'veicle_data')
      seg_types = Seguro.where(tipo_veiculo: self.vei_tipo)
      p "Definindo valor inicial do seguro PARTE 1"
      seg_types.each do |seguro|
        p "veiculo #{self.vei_tipo}"
        p "nacionalidade #{self.vei_nacionalidade}"
        p "valor do seguro atual #{self.seguro_preco_default}"
        p "preco do carro #{self.vei_preco}"
        p "valor inicial #{seguro.valor_incial}"
        p "valor inicial #{seguro.valor_final}"
        p "valor do seguro seguro #{seguro.preco_default}"
        p "seguro para #{seguro.tipo_veiculo}"
        if (self.vei_tipo != 'Carros')
          p "nao eh carro"
          if (self.seguro_preco_default.nil? && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final) && self.vei_tipo == seguro.tipo_veiculo || (self.seguro_preco_default != seguro.preco_default && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final) && self.vei_tipo == seguro.tipo_veiculo) )
              p "deu match"
              p "Definindo valor inicial do seguro IF PARTE 2"
              self.seguro_preco_default = seguro.preco_default
              self.seguro_preco_silver = seguro.preco_silver
              self.seguro_preco_pro = seguro.preco_pro

              p "Seguro definido no IF #{self.seguro_preco_default}"
              self.save
            end
            elsif ( (self.seguro_preco_default.nil? && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final)  && self.vei_tipo == seguro.tipo_veiculo   && self.vei_nacionalidade == 'Nacional') || (self.seguro_preco_default != seguro.preco_default && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final) && self.vei_tipo == seguro.tipo_veiculo && self.vei_nacionalidade == 'Nacional' ))
              p "carro NACIONAL"
              self.seguro_preco_default = seguro.preco_default
              self.seguro_preco_silver = seguro.preco_silver
              self.seguro_preco_pro = seguro.preco_pro              
              self.save
              elsif ((self.seguro_preco_default.nil? && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final) && self.vei_tipo == 'Carros' && seguro.tipo_veiculo == self.vei_nacionalidade ) || (self.seguro_preco_default != seguro.preco_default && self.vei_preco.between?(seguro.valor_incial,seguro.valor_final) && self.vei_tipo == 'Carros' && seguro.tipo_veiculo == self.vei_nacionalidade))
                p "carro IMIPORTADO"
              self.seguro_preco_default = seguro.preco_default
              self.seguro_preco_silver = seguro.preco_silver
              self.seguro_preco_pro = seguro.preco_pro
              self.save
        end 
      end
    end
  end

  
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController
  before_action :set_orcamento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :show, :destroy]

  # GET /orcamentos
  # GET /orcamentos.json
  def index

    @orcamentos = Orcamento.all
  end

  # GET /orcamentos/1
  # GET /orcamentos/1.json
  def show

  end

  def finish
   @orcamento = Orcamento.find(params[:_id])  
  end

  # GET /orcamentos/new
  def new
    @orcamento = Orcamento.new
  end

  # GET /orcamentos/1/edit
  def edit

  end

  # POST /orcamentos
  # POST /orcamentos.json
  def create
    @orcamento = Orcamento.new(orcamento_params)

    respond_to do |format|
      if @orcamento.save
        format.html { redirect_to steps_path(@orcamento, :_id => @orcamento._id) }
        format.json { render :show, status: :created, location: @orcamento }
      else
        format.html { render :new }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orcamentos/1
  # PATCH/PUT /orcamentos/1.json
  def update
    respond_to do |format|
      if @orcamento.update(orcamento_params)
        format.html { redirect_to steps_path(@orcamento, :_id => @orcamento._id) }
        format.json { render :show, status: :ok, location: @orcamento }
      else
        format.html { render :edit }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcamentos/1
  # DELETE /orcamentos/1.json
  def destroy
    @orcamento.destroy
    respond_to do |format|
      format.html { redirect_to orcamentos_url, notice: 'Orcamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orcamento
      @orcamento = Orcamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orcamento_params
    params.require(:orcamento).permit(:data_pgto,:seguro_plan, :seguro_preco_default, :seguro_preco_silver, :seguro_preco_pro,:current_step, :cli_name, :cli_email, :cli_tel, :cli_cpf, :cli_pais, :cli_trab, :cli_salario, :cli_sexo, :cli_cep, :cli_end, :cli_end_number, :cli_end_compl, :cli_end_cidade, :cli_end_bairro, :vei_tipo, :vei_marca, :vei_veiculo, :vei_modelo_ano, :vei_preco, :vei_tipo_uso, :vei_placa,:seguro_preco,:seguro_preco_final, :seg_car_reboque_300, :seg_car_reboque_500 , :seg_car_terceiros_50k , :seg_car_vidros , :seg_car_reserva_7d , :seg_car_reserva14, :vei_nacionalidade)
    end 
end

app/views/orcamentos/_form.html.erb
<%= form_for(orcamento) do |f| %>
  <% if orcamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orcamento.errors.count, "error") %> prohibited this orcamento from being saved:</h2>

      <ul>
      <% orcamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner clearfix"><div class="wpb_wrapper wt_wpb_wrapper clearfix">
  <div class="wpb_single_image wpb_content_element vc_align_left  wpb_animate_when_almost_visible wpb_left-to-right vc_custom_1478020438959 wpb_start_animation">
    
    <figure class="wpb_wrapper vc_figure">
      <div class="vc_single_image-wrapper   vc_box_border_grey"><img width="191" height="300" src="http://coteauto.com.br/wp-content/uploads/2014/11/mascote-191x300.png" class="vc_single_image-img attachment-medium" alt="mascote" srcset="http://coteauto.com.br/wp-content/uploads/2014/11/mascote-191x300.png 191w, http://coteauto.com.br/wp-content/uploads/2014/11/mascote-651x1024.png 651w, http://coteauto.com.br/wp-content/uploads/2014/11/mascote.png 682w" sizes="(max-width: 191px) 100vw, 191px"></div>
    </figure>
  </div>
</div></div>
</div>

<%= f.hidden_field :current_step , :value => 'new'%>

<div class="col-sm-6">
<div clas="row">
<h3 text-color="red"> Seu veículo merece esta proteção!</h3>
<div class="col-md-3">
  <%= image_tag '/images/sports-car.png' , class: 'image-responsive' %>
</div>
<div class="col-md-3">
  <%= image_tag '/images/motorbike.png' , class: 'image-responsive' %>
</div>
<div class="col-md-3">
  <%= image_tag '/images/truck.png' , class: 'image-responsive' %>
</div>
<div class="col-md-3">
  <%= image_tag '/images/ocean-transportation.png' , class: 'image-responsive' %>
</div>

</div>
  <h4> Oi, a gente quer conhecer você melhor, é rapidinho </h4>
  <strong> menos de 1 minutinho </strong>
  <br>
  <br>


  <div class="field" id="nome">
    Meu nome é   <%= f.text_field :cli_name , class: "form_input-text" , placeholder: "nome", required: true %>
    </div>
  <div class="field" id="phone">

    Se a <strong>Cote Auto</strong> precisar falar comigo, pode me ligar no : <%= f.telephone_field :cli_tel , class: "form_input-text", placeholder: "(XX) XXXX-XXXX" , required: true %>
  </div>
  <div class="field" id="email">

  ou mandar um e-mail para <%= f.email_field :cli_email , class: "form_input-text" , placeholder: "nome@email.com" , required: true%>

  </div>

  <div class="actions ">
    <%= f.submit 'Próximo passo', :class => 'btn btn-primary' %>
  </div>

  </div>
<% end %>

app/views/orcamentos/edit.html.erb
<h1>Editing Orcamento</h1>

<%= render 'form', orcamento: @orcamento %>

<%= link_to 'Show', @orcamento %> |
<%= link_to 'Back', orcamentos_path %>

app/views/orcamentos/index.html.erb
    <% content_for :head do %>

      <%= render 'pixels/index' %>
      <p> teste</p>
    
    <%end%>

<p id="notice"><%= notice %></p>

<h1>Orcamentos</h1>

<table>
  <thead>
    <tr>
      <th>Cli name</th>
      <th>Cli email</th>
      <th>Cli tel</th>
      <th>Cli cpf</th>
      <th>Cli pais</th>
      <th>Cli sexo</th>
      <th>Cli cep</th>
      <th>Cli end</th>
      <th>Cli end number</th>
      <th>Cli end compl</th>
      <th>Cli end cidade</th>
      <th>Cli end bairro</th>
      <th>Vei tipo</th>
      <th>Vei marca</th>
      <th>Vei veiculo</th>
      <th>Vei modelo ano</th>
      <th>Vei preco</th>
      <th>Vei tipo uso</th>
      <th>Vei placa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orcamentos.each do |orcamento| %>
      <tr>
        <td><%= orcamento.cli_name %></td>
        <td><%= orcamento.cli_email %></td>
        <td><%= orcamento.cli_tel %></td>
        <td><%= orcamento.cli_cpf %></td>
        <td><%= orcamento.cli_pais %></td>
        <td><%= orcamento.cli_sexo %></td>
        <td><%= orcamento.cli_cep %></td>
        <td><%= orcamento.cli_end %></td>
        <td><%= orcamento.cli_end_number %></td>
        <td><%= orcamento.cli_end_compl %></td>
        <td><%= orcamento.cli_end_cidade %></td>
        <td><%= orcamento.cli_end_bairro %></td>
        <td><%= orcamento.vei_tipo %></td>
        <td><%= orcamento.vei_marca %></td>
        <td><%= orcamento.vei_veiculo %></td>
        <td><%= orcamento.vei_modelo_ano %></td>
        <td><%= orcamento.vei_preco %></td>
        <td><%= orcamento.vei_tipo_uso %></td>
        <td><%= orcamento.vei_placa %></td>
        <td><%= link_to 'Show', orcamento %></td>
        <td><%= link_to 'Edit', edit_orcamento_path(orcamento) %></td>
        <td><%= link_to 'Destroy', orcamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orcamento', new_orcamento_path %>

app/views/orcamentos/new.html.erb
    <% content_for :head do %>

      <%= render 'pixels/index' %>
 
    <%end%>
    
<%= render 'form', orcamento: @orcamento %>

app/views/orcamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cli name:</strong>
  <%= @orcamento.cli_name %>
</p>

<p>
  <strong>Cli email:</strong>
  <%= @orcamento.cli_email %>
</p>

<p>
  <strong>Cli tel:</strong>
  <%= @orcamento.cli_tel %>
</p>

<p>
  <strong>Cli cpf:</strong>
  <%= @orcamento.cli_cpf %>
</p>

<p>
  <strong>Cli pais:</strong>
  <%= @orcamento.cli_pais %>
</p>

<p>
  <strong>Cli trab:</strong>
  <%= @orcamento.cli_trab %>
</p>

<p>
  <strong>Cli salario:</strong>
  <%= @orcamento.cli_salario %>
</p>

<p>
  <strong>Cli sexo:</strong>
  <%= @orcamento.cli_sexo %>
</p>

<p>
  <strong>Cli cep:</strong>
  <%= @orcamento.cli_cep %>
</p>

<p>
  <strong>Cli end:</strong>
  <%= @orcamento.cli_end %>
</p>

<p>
  <strong>Cli end number:</strong>
  <%= @orcamento.cli_end_number %>
</p>

<p>
  <strong>Cli end compl:</strong>
  <%= @orcamento.cli_end_compl %>
</p>

<p>
  <strong>Cli end cidade:</strong>
  <%= @orcamento.cli_end_cidade %>
</p>

<p>
  <strong>Cli end bairro:</strong>
  <%= @orcamento.cli_end_bairro %>
</p>

<p>
  <strong>Vei tipo:</strong>
  <%= @orcamento.vei_tipo %>
</p>

<p>
  <strong>Vei marca:</strong>
  <%= @orcamento.vei_marca %>
</p>

<p>
  <strong>Vei veiculo:</strong>
  <%= @orcamento.vei_veiculo %>
</p>

<p>
  <strong>Vei modelo ano:</strong>
  <%= @orcamento.vei_modelo_ano %>
</p>

<p>
  <strong>Vei preco:</strong>
  <%= @orcamento.vei_preco %>
</p>

<p>
  <strong>Vei tipo uso:</strong>
  <%= @orcamento.vei_tipo_uso %>
</p>

<p>
  <strong>Vei placa:</strong>
  <%= @orcamento.vei_placa %>
</p>

<%= link_to 'Edit', edit_orcamento_path(@orcamento) %> |
<%= link_to 'Back', orcamentos_path %>